// Copyright 2026 Shazron Abdullah and Bunyi contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System.Text.Json;
using Bunyi.Core.Audio;
using Xunit;

namespace Bunyi.Core.Tests;

/// <summary>
/// The mel spectrogram, checked against librosa rather than against itself.
/// </summary>
/// <remarks>
/// <para>
/// The reference pipeline uses librosa, so "correct" here means "what librosa
/// returns" — not "a defensible mel spectrogram". The fixture was produced by
/// running librosa; <c>gen_mel_truth.py</c> alongside it is how.
/// </para>
/// <para>
/// The input is generated by an integer LCG on both sides rather than stored,
/// so the two implementations start from bit-identical samples and the only
/// thing under test is the spectrogram. Storing a few thousand floats would
/// have put a rounding question between us and the answer.
/// </para>
/// </remarks>
public sealed class MelSpectrogramTests
{
    // Declared before Truth on purpose: static initialisers run in order, and
    // loading the fixture reads these. The other way round they are null, the
    // match silently becomes case-sensitive, and every field comes back empty.
    private static readonly JsonSerializerOptions JsonOptions =
        new() { PropertyNameCaseInsensitive = true };

    private static readonly MelTruth Truth = LoadTruth();


    // ---- The whole thing, end to end ----

    [Fact]
    public void Matches_what_librosa_produces()
    {
        var audio = Signal(Truth.Lcg.Samples, Truth.Lcg.Scale);

        var mel = MelSpectrogram.Compute(audio);

        Assert.Equal(Truth.LogMel.Count, mel.Frames);
        Assert.Equal(MelSpectrogram.MelCount, mel.Bins);

        var worst = 0.0;
        for (var frame = 0; frame < mel.Frames; frame++)
        {
            for (var bin = 0; bin < mel.Bins; bin++)
            {
                worst = Math.Max(worst, Math.Abs(Truth.LogMel[frame][bin] - mel[frame, bin]));
            }
        }

        // Not exact, and cannot be: librosa does this in single precision while
        // we accumulate in double. Measured at 7.2e-07, which is float rounding
        // and nothing else — so the bar is set near it rather than at some
        // comfortable distance. A wrong scale, window or filterbank misses by
        // whole units, but a subtly wrong one might not, and that is the case
        // worth catching.
        Assert.True(worst < 1e-5, $"worst disagreement with librosa was {worst}");
    }

    // ---- The filterbank, band by band ----

    [Fact]
    public void Every_band_covers_the_bins_librosa_gives_it()
    {
        // Where each triangle starts and stops is set by the mel scale. HTK's
        // formula would place all 128 of them differently — and still produce a
        // perfectly plausible spectrogram.
        var filters = MelSpectrogram.BuildFilterbank();

        for (var mel = 0; mel < filters.Length; mel++)
        {
            var nonZero = Enumerable.Range(0, filters[mel].Length)
                .Where(bin => filters[mel][bin] > 0.0)
                .ToList();

            Assert.Equal(Truth.Filterbank[mel].First, nonZero.Count > 0 ? nonZero[0] : -1);
            Assert.Equal(Truth.Filterbank[mel].Last, nonZero.Count > 0 ? nonZero[^1] : -1);
        }
    }

    [Fact]
    public void Every_band_weighs_what_librosa_says()
    {
        // The area normalisation. Peak normalisation is the usual alternative,
        // gives every band a peak of 1.0, and would drown the low end.
        var filters = MelSpectrogram.BuildFilterbank();

        for (var mel = 0; mel < filters.Length; mel++)
        {
            Assert.Equal(Truth.Filterbank[mel].Sum, filters[mel].Sum(), precision: 6);
            Assert.Equal(Truth.Filterbank[mel].Peak, filters[mel].Max(), precision: 6);
        }
    }

    [Fact]
    public void Low_bands_are_narrower_than_high_ones()
    {
        // The point of a mel scale. Stated separately because the fixture would
        // still pass if both it and we were wrong in the same direction, and
        // this is the one property that needs no oracle.
        var filters = MelSpectrogram.BuildFilterbank();
        int Width(int mel) => filters[mel].Count(w => w > 0.0);

        Assert.True(Width(0) < Width(127), "the filterbank is not mel-spaced at all");
        Assert.True(Width(10) < Width(100));
    }

    // ---- The mel scale itself ----

    [Fact]
    public void The_scale_is_linear_below_a_kilohertz_and_logarithmic_above()
    {
        // Slaney's shape. The kink at 1 kHz is the whole difference from HTK.
        Assert.Equal(0.0, MelSpectrogram.HzToMel(0.0), precision: 9);
        Assert.Equal(15.0, MelSpectrogram.HzToMel(1000.0), precision: 9);

        // Below the kink, doubling the hertz doubles the mels exactly.
        Assert.Equal(
            2.0 * MelSpectrogram.HzToMel(300.0),
            MelSpectrogram.HzToMel(600.0),
            precision: 9);

        // Above it, that stops being true.
        Assert.True(MelSpectrogram.HzToMel(8000.0) < 2.0 * MelSpectrogram.HzToMel(4000.0));
    }

    [Theory]
    [InlineData(0.0)]
    [InlineData(120.0)]
    [InlineData(999.9)]
    [InlineData(1000.0)]
    [InlineData(4000.0)]
    [InlineData(12000.0)]
    public void Converting_back_returns_the_same_frequency(double hz)
    {
        Assert.Equal(hz, MelSpectrogram.MelToHz(MelSpectrogram.HzToMel(hz)), precision: 6);
    }

    // ---- Framing ----

    [Fact]
    public void Frames_are_counted_the_uncentred_way()
    {
        // center=False in the reference: no padding at either end, so the count
        // is what fits. Centred framing would add frames and shift every one of
        // them by half a window.
        Assert.Equal(1, MelSpectrogram.Compute(new float[1024]).Frames);
        Assert.Equal(2, MelSpectrogram.Compute(new float[1024 + 256]).Frames);
        Assert.Equal(13, MelSpectrogram.Compute(new float[4096]).Frames);
    }

    [Fact]
    public void A_clip_shorter_than_one_window_has_no_frames()
    {
        // Better than one frame of mostly padding, which would be a spectrum of
        // something that was never recorded.
        var mel = MelSpectrogram.Compute(new float[1023]);

        Assert.Equal(0, mel.Frames);
        Assert.Empty(mel.Values);
    }

    [Fact]
    public void Silence_sits_on_the_floor()
    {
        var mel = MelSpectrogram.Compute(new float[4096]);

        for (var frame = 0; frame < mel.Frames; frame++)
        {
            for (var bin = 0; bin < mel.Bins; bin++)
            {
                Assert.Equal((float)Math.Log(MelSpectrogram.Floor), mel[frame, bin]);
            }
        }
    }

    // ---- The window ----

    [Fact]
    public void The_window_is_periodic_rather_than_symmetric()
    {
        // Periodic divides by n, symmetric by n - 1. The giveaway is that a
        // periodic window never returns to zero at the end.
        var w = MelSpectrogram.HannPeriodic(8);

        Assert.Equal(0.0, w[0], precision: 12);
        Assert.Equal(1.0, w[4], precision: 12);
        Assert.NotEqual(0.0, w[7]);
        Assert.Equal(w[1], w[7], 12);
    }

    // ---- Fixture plumbing ----

    /// <summary>
    /// The same pseudo-random samples the fixture generator used.
    /// </summary>
    /// <remarks>
    /// Plain 64-bit integer arithmetic, which C# and NumPy agree on exactly.
    /// Noise rather than a tone on purpose: it puts energy in every band, so a
    /// filterbank that is wrong anywhere has nowhere to hide.
    /// </remarks>
    private static float[] Signal(int count, double scale)
    {
        var state = 0x2545F4914F6CDD1DUL;
        var samples = new float[count];

        for (var i = 0; i < count; i++)
        {
            state = (state * 6364136223846793005UL) + 1442695040888963407UL;
            var unit = (state >> 11) / (double)(1UL << 53);
            samples[i] = (float)(((unit * 2.0) - 1.0) * scale);
        }

        return samples;
    }

    private static MelTruth LoadTruth()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Fixtures", "mel-truth.json");
        using var stream = File.OpenRead(path);
        return JsonSerializer.Deserialize<MelTruth>(stream, JsonOptions)
            ?? throw new InvalidOperationException("mel-truth.json did not parse.");
    }


    public sealed record MelTruth(
        LcgSpec Lcg,
        IReadOnlyList<FilterSpec> Filterbank,
        IReadOnlyList<IReadOnlyList<double>> LogMel);

    public sealed record LcgSpec(int Samples, double Scale);

    public sealed record FilterSpec(int First, int Last, double Sum, double Peak);
}
