# Copyright 2026 Shazron Abdullah and Bunyi contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Not run by the build. It is here so mel-truth.json can be regenerated, and so
# the next person can see exactly which librosa call the C# is held to:
#
#   python -m venv venv && venv/bin/pip install librosa
#   venv/bin/python gen_mel_truth.py

"""Ground truth for the mel spectrogram, straight from librosa.

The input is generated by an integer LCG so the C# side can reproduce it
exactly rather than us shipping a few thousand floats and hoping they round
trip. Same arithmetic, same bits, on both sides.
"""
import json, numpy as np, librosa

SR, N_FFT, HOP, WIN, N_MELS, FMIN, FMAX = 24000, 1024, 256, 1024, 128, 0, 12000
MASK = (1 << 64) - 1

def lcg(n, seed=0x2545F4914F6CDD1D):
    s, out = seed, []
    for _ in range(n):
        s = (s * 6364136223846793005 + 1442695040888963407) & MASK
        out.append(((s >> 11) / float(1 << 53)) * 2.0 - 1.0)
    return np.asarray(out, dtype=np.float32)

n_samples = 4096
audio = (lcg(n_samples) * 0.5).astype(np.float32)

mel = librosa.feature.melspectrogram(
    y=audio, sr=SR, n_fft=N_FFT, hop_length=HOP, win_length=WIN,
    n_mels=N_MELS, fmin=FMIN, fmax=FMAX, center=False)
logmel = np.log(np.clip(mel, a_min=1e-5, a_max=None))

clipped = int((mel < 1e-5).sum())
print(f"mel {mel.shape}  frames={mel.shape[1]}  clipped={clipped}/{mel.size}"
      f" ({100*clipped/mel.size:.1f}%)")

fb = librosa.filters.mel(sr=SR, n_fft=N_FFT, n_mels=N_MELS, fmin=FMIN, fmax=FMAX)
print(f"filterbank {fb.shape}  sum={fb.sum():.6f}")

# Per-filter shape: where it starts, where it ends, how much it weighs.
# A filterbank that is wrong anywhere is wrong in one of these.
rows = []
for i in range(N_MELS):
    nz = np.nonzero(fb[i])[0]
    rows.append({
        "first": int(nz[0]) if nz.size else -1,
        "last": int(nz[-1]) if nz.size else -1,
        "sum": round(float(fb[i].sum()), 9),
        "peak": round(float(fb[i].max()), 9),
    })

truth = {
    "_comment": "Generated by librosa %s. See gen_mel_truth.py." % librosa.__version__,
    "librosa": librosa.__version__,
    "params": {"sr": SR, "n_fft": N_FFT, "hop": HOP, "win": WIN,
               "n_mels": N_MELS, "fmin": FMIN, "fmax": FMAX, "center": False},
    "lcg": {"seed": "0x2545F4914F6CDD1D", "mult": "6364136223846793005",
            "inc": "1442695040888963407", "scale": 0.5, "samples": n_samples},
    "filterbank": rows,
    "logMel": [[round(float(v), 6) for v in logmel[:, t]] for t in range(logmel.shape[1])],
}

out = r"C:\Users\shazron\Documents\git\home\github.com\shaztechio\bunyi-app\apps\dotnet\tests\Core.Tests\Fixtures\mel-truth.json"
with open(out, "w", encoding="utf-8") as f:
    json.dump(truth, f, indent=1)
print("wrote", out)
