#!/bin/bash
# Copyright 2026 Shazron Abdullah and Bunyi contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Developer ID signs, notarizes, and staples dist/macos/Bunyi.app.
#
#   BUNYI_SIGN_IDENTITY   full name of the Developer ID Application identity.
#                         Optional when exactly one is installed.
#
# Notarization credentials, either:
#   BUNYI_NOTARY_PROFILE  notarytool keychain profile (default: bunyi)
# or, for CI, where no keychain profile exists:
#   BUNYI_APPLE_ID        Apple ID email
#   BUNYI_TEAM_ID         Developer Team ID
#   BUNYI_APP_PASSWORD    app-specific password
#
# Run apps/macos/build-dist.sh first. This script never builds, so what gets
# notarized is exactly what was tested.

set -euo pipefail

# Resolve the repository root from this script's location rather than requiring
# a particular working directory: every path below is absolute from here.
root="$(cd "$(dirname "$0")/../../../.." && pwd)"
app="$root/dist/macos/Bunyi.app"
# Generated by XcodeGen from apps/macos/project.yml, so it exists only after a
# build — which is the same precondition as the app itself.
entitlements="$root/apps/macos/Bunyi.entitlements"
profile="${BUNYI_NOTARY_PROFILE:-bunyi}"

if [ ! -d "$app" ]; then
  printf 'error: %s does not exist. Run apps/macos/build-dist.sh first.\n' "$app" >&2
  exit 1
fi

if [ ! -f "$entitlements" ]; then
  printf 'error: %s is missing. It is generated by `xcodegen generate`.\n' "$entitlements" >&2
  exit 1
fi

identity="${BUNYI_SIGN_IDENTITY:-}"
if [ -z "$identity" ]; then
  # Exactly one Developer ID Application identity is the normal case; more than
  # one has to be chosen deliberately rather than guessed at.
  # Read into an array the long way: macOS ships bash 3.2, which has no mapfile.
  found=()
  while IFS= read -r line; do
    [ -n "$line" ] && found+=("$line")
  done < <(security find-identity -v -p codesigning \
    | sed -n 's/.*"\(Developer ID Application: [^"]*\)".*/\1/p')
  if [ "${#found[@]}" -eq 1 ]; then
    identity="${found[0]}"
  elif [ "${#found[@]}" -eq 0 ]; then
    printf 'error: no Developer ID Application certificate found.\n' >&2
    printf 'Create one in Xcode: Settings > Accounts > Manage Certificates > + > Developer ID Application.\n' >&2
    exit 1
  else
    printf 'error: several Developer ID Application certificates found. Set BUNYI_SIGN_IDENTITY to one of:\n' >&2
    printf '  %s\n' "${found[@]}" >&2
    exit 1
  fi
fi
printf 'Signing as: %s\n' "$identity"

# A "*.cstemp" left behind by an interrupted or --deep signing run gets sealed
# into CodeResources by the next signature, and the bundle then fails
# verification naming a file that no longer exists. Clear them before signing
# rather than debugging it afterwards.
find "$app" -name '*.cstemp' -delete

# Nested code signs first. --deep is deliberately not used: it is deprecated and
# applies the app's entitlements to nested bundles, which is not what any of
# them should carry.
help_bundle="$app/Contents/Resources/Bunyi.help"
if [ -d "$help_bundle" ]; then
  codesign --force --options runtime --timestamp --sign "$identity" "$help_bundle"
fi

# The Swift runtime and MLX ship as frameworks inside the bundle, and each one
# is code that Gatekeeper evaluates separately. Signing them before the outer
# bundle is what makes the outer signature seal a tree that already verifies.
if [ -d "$app/Contents/Frameworks" ]; then
  while IFS= read -r framework; do
    codesign --force --options runtime --timestamp --sign "$identity" "$framework"
  done < <(find "$app/Contents/Frameworks" -maxdepth 1 -type d -name '*.framework' -o -maxdepth 1 -name '*.dylib')
fi

codesign --force --options runtime --timestamp \
  --entitlements "$entitlements" \
  --sign "$identity" "$app"

codesign --verify --strict --verbose=2 "$app"

# The sandbox entitlement is why the models folder resolves inside the app
# container. A build that loses it still launches and looks fine, then reads an
# empty Application Support directory and re-downloads gigabytes of models.
if ! codesign -d --entitlements - "$app" 2>/dev/null \
    | grep -q 'com.apple.security.app-sandbox'; then
  printf 'error: the sandbox entitlement is missing from the signed app.\n' >&2
  printf 'Bunyi would launch normally and lose track of every downloaded model.\n' >&2
  exit 1
fi
# Without the network entitlement the first download fails inside the sandbox
# with an error that looks like the user's connection, not like a signing bug.
if ! codesign -d --entitlements - "$app" 2>/dev/null \
    | grep -q 'com.apple.security.network.client'; then
  printf 'error: the network entitlement is missing from the signed app.\n' >&2
  printf 'Bunyi could never download a model.\n' >&2
  exit 1
fi
printf 'Sandbox and network entitlements present.\n'

# A CI runner has no keychain profile, so credentials can be passed directly.
# They are only ever read from the environment: putting an app-specific password
# on the command line would expose it in the process list.
notarize() {
  if [ -n "${BUNYI_APPLE_ID:-}" ] && [ -n "${BUNYI_TEAM_ID:-}" ] \
     && [ -n "${BUNYI_APP_PASSWORD:-}" ]; then
    xcrun notarytool submit "$1" \
      --apple-id "$BUNYI_APPLE_ID" \
      --team-id "$BUNYI_TEAM_ID" \
      --password "$BUNYI_APP_PASSWORD" \
      --wait
  else
    xcrun notarytool submit "$1" --keychain-profile "$profile" --wait
  fi
}

printf 'Submitting the app for notarization…\n'
archive="$root/dist/macos/Bunyi-notarize.zip"
rm -f "$archive"
ditto -c -k --keepParent "$app" "$archive"
notarize "$archive"
rm -f "$archive"

xcrun stapler staple "$app"
spctl --assess --type execute --verbose=4 "$app"

# The app is stapled before it goes into the image, and the image is notarized
# separately afterwards. Two submissions, deliberately: notarizing only the
# image would leave the app with no ticket of its own, so dragging it out and
# launching it offline would fail its first check.
printf '\nBuilding the disk image…\n'
"$root/apps/macos/tools/packaging/make-dmg.sh"
dmg="$(ls -t "$root"/dist/macos/Bunyi-*.dmg | head -1)"

printf 'Submitting the disk image for notarization…\n'
notarize "$dmg"
xcrun stapler staple "$dmg"
xcrun stapler validate "$dmg"
spctl --assess --type open --context context:primary-signature --verbose=4 "$dmg"

printf '\nSigned, notarized, and stapled:\n'
printf '  %s\n' "$app"
printf '  %s\n' "$dmg"
printf 'Generate speech in each mode before distributing it.\n'
